apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: hareon/frontend
  interval: 1m0s
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: backend
  namespace: flux-system
spec:
  image: hareon/backend
  interval: 1m0s
  provider: generic
