apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-server
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/my-cluster/apps/test-server" # test
  prune: true
  targetNamespace: default
  wait: true